language: r
dist: xenial
r:
  - release
  - devel
cache: packages

latex: false

os: linux
compiler: gcc
addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages:
      - libgsl-dev
      - libv8-dev
env:
  - CXX_OLEVEL=2 CXX=g++ _R_CHECK_DONTTEST_EXAMPLES_=false

matrix:
  include:
    r: release
    name: old-tidyverse
    before_script: Rscript -e "remotes::install_version('dplyr', '0.8.5'); remotes::install_version('tibble', '2.1.3'); remotes::install_version('tidyr', '1.0.0');"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - mkdir -p ~/.R/
  - chmod +x configure
  - echo "CXX = `R CMD config CXX`" >> ~/.R/Makevars
  - echo "CXXFLAGS = `R CMD config CXXFLAGS` -pedantic -g0 -flto" >> ~/.R/Makevars
  - echo "LDFLAGS += -flto" >> ~/.R/Makevars
  - export CLANG_EXTRA_ARG=""
  - if [[ $CXX = "clang++" ]] ;  then export CLANG_EXTRA_ARG=" -Qunused-arguments -fcolor-diagnostics " ; fi
  - sed -i.bak "s/ g++/ ${CXX}${CLANG_EXTRA_ARG}/" ~/.R/Makevars
  - sed -i.bak "s/O[0-3]/O$CXX_OLEVEL/" ~/.R/Makevars
  - echo "options(repos = c(CRAN = 'https://packagemanager.rstudio.com/all/__linux__/xenial/latest'))" >> ~/.Rprofile.site
  - echo "options(HTTPUserAgent = paste0('R/', getRversion(), ' R (',
       paste(getRversion(), R.version['platform'], R.version['arch'], R.version['os']),
       ')'))" >> ~/.Rprofile.site
